apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "kepler.fullname" .}}
  namespace: {{include "kepler.namespace" .}}
  labels:
    {{- include "kepler.labels" . | nindent 4}}
  {{- with .Values.annotations}}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end}}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4}}
{{- if .Values.vmagent.enabled }}
  vmagent-scrape.yaml: |
    global:
      scrape_interval: {{ .Values.vmagent.scrape.interval | quote }}
    scrape_configs:
      - job_name: "kepler-local"
        metrics_path: {{ .Values.vmagent.scrape.path | quote }}
        scheme: {{ .Values.vmagent.scrape.scheme | quote }}
        static_configs:
          - targets:
              - {{ .Values.vmagent.scrape.target | quote }}
{{- end }}