image:
  repository: gitlab.lrz.de:5005/green-it/students/bachelor/eder-moritz
  pullPolicy: Always
  tag: "test"

imagePullSecrets:
  - name: gitlab-registry-creds

namespace:
  create: false
  name: default

serviceAccount:
  create: true
  name: kepler

rbac:
  create: true

service:
  type: ClusterIP
  port: 28282
  targetPort: http
  protocol: TCP

daemonset:
  hostPID: true
  tolerations:
  nodeSelector: {}
  affinity: {}
  hostUsers: true
  securityContext:
    privileged: true
    runAsNonRoot: false

config:
  log:
    level: info
    format: text
  host:
    sysfs: /host/sys
    procfs: /host/proc
  monitor:
    interval: 5s
    staleness: 30s
    maxTerminated: 100
    minTerminatedEnergyThreshold: 10
  rapl:
    zones: []
  exporter:
    stdout:
      enabled: false
    prometheus:
      enabled: true
      debugCollectors:
        - go
      metricsLevel:
        - node
        - process
  web:
    configFile: ""
    listenAddresses:
      - :28282
  debug:
    pprof:
      enabled: false
  kube:
    enabled: false
    config: ""
    nodeName: ""
    podInformer:
      mode: kubelet
      pollInterval: 15s
  dev:
    fake-cpu-meter:
      enabled: false
      zones: []
  experimental:
    prometheus-power:
      nodeDeviceMapFile: /etc/kepler/node-device-map/node-device-map.yaml
      caFile: /etc/prompower-ca/ca.crt
      enabled: true
      baseURL: https://vmuser:VMInHochschule@192.168.64.1:8428
      query: device_power_watts_avg{room="R3.033",rack="Rack 3",device="${POWER_DEVICE}"}
    platform:
      redfish:
        enabled: false
        configFile: /etc/kepler/redfish.yaml
        nodeName: ""
    hwmon:
      enabled: false
      zones: []
      chipRules: []
    gpu:
      enabled: false
      idlePower: 0
      dcgmEndpoint: ""

serviceMonitor:
  enabled: false

networkPolicy:
  enabled: false

labels:
  room: R3.033
  rack: Rack-3

annotations: {}